version: '3.8'

services:
  node_a:
    build: .
    container_name: node_a
    networks:
      p2p_network:
        ipv4_address: 172.20.0.10
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    command: ["--port", "8080"]

  node_b:
    build: .
    container_name: node_b
    networks:
      p2p_network:
        ipv4_address: 172.20.0.11
    tty: true
    stdin_open: true
    ports:
      - "8081:8080"
    command: ["--port", "8080"]

  node_c:
    build: .
    container_name: node_c
    networks:
      p2p_network:
        ipv4_address: 172.20.0.12
    tty: true
    stdin_open: true
    ports:
      - "8082:8080"
    command: ["--port", "8080"]
    # Configurato come nodo malizioso per il test Zero-Trust
    environment:
      - NODE_BEHAVIOR=MALICIOUS

  node_d:
    build: .
    container_name: node_d
    networks:
      p2p_network:
        ipv4_address: 172.20.0.13
    tty: true
    stdin_open: true
    ports:
      - "8083:8080"
    command: ["--port", "8080"]

  node_e:
    build: .
    container_name: node_e
    networks:
      p2p_network:
        ipv4_address: 172.20.0.14
    tty: true
    stdin_open: true
    ports:
      - "8084:8080"
    command: ["--port", "8080"]

  node_g:
    build: .
    container_name: node_g
    networks:
      p2p_network:
        ipv4_address: 172.20.0.16
    tty: true
    stdin_open: true
    ports:
      - "8086:8080"
    command: ["--port", "8080"]

networks:
  p2p_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
