#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <getopt.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include "sgx_urts.h"
#include "enclave_u.h" // Generated by edger8r automatically

#define DEFAULT_PORT 5005
#define ENCLAVE_FILENAME "enclave.signed.so"

// Global enclave ID required for ECALLs
sgx_enclave_id_t global_eid = 0;

/**
 * Implementation of the OCALL declared in enclave.edl.
 * Allows the trusted enclave to securely print logs back to the untrusted host terminal.
 */
void ocall_print_string(const char *str) {
    if (str != NULL) {
        printf("%s", str);
        fflush(stdout); 
    }
}

/**
 * Prints the application CLI usage instructions.
 */
void print_usage(const char* launch_name) {
    printf("Usage: %s [options]\n", launch_name);
    printf("Options:\n");
    printf("  -m, --mode <listen|connect>  Set node execution mode (Required)\n");
    printf("  -i, --ip <ip_address>        Target peer IP address (Required for connect mode)\n");
    printf("  -p, --port <port_number>     Port number (Default: %d)\n", DEFAULT_PORT);
    printf("  -h, --help                   Show this help message\n");
}

/**
 * Initializes the Intel SGX Enclave in the specified mode.
 */
int init_enclave(void) {
    sgx_status_t ret = SGX_SUCCESS;
    sgx_launch_token_t token = {0};
    int updated = 0;
    
    // In simulation mode (SGX_MODE=SIM), hardware token enforcement is bypassed
    ret = sgx_create_enclave(ENCLAVE_FILENAME, SGX_DEBUG_FLAG, &token, &updated, &global_eid, NULL);
    if (ret != SGX_SUCCESS) {
        printf("[HOST_ERROR] Failed to create SGX enclave. Error code: 0x%X\n", ret);
        return -1;
    }
    printf("[HOST] SGX Enclave initialized successfully. EID: %lu (SIMULATION MODE)\n", global_eid);
    return 0;
}

int main(int argc, char* argv[]) {
    int opt;
    char* mode = NULL;
    char* peer_ip = NULL;
    int port = DEFAULT_PORT;

    // Network variables
    int server_fd, new_socket, client_fd;
    struct sockaddr_in address;
    int opt_sock = 1;
    int addrlen = sizeof(address);
    char buffer[1024] = {0};

    struct option long_options[] = {
        {"mode", required_argument, 0, 'm'},
        {"ip", required_argument, 0, 'i'},
        {"port", required_argument, 0, 'p'},
        {"help", no_argument, 0, 'h'},
        {0, 0, 0, 0}
    };

    // Parsing command line options
    while ((opt = getopt_long(argc, argv, "m:i:p:h", long_options, NULL)) != -1) {
        switch (opt) {
            case 'm': mode = optarg; break;
            case 'i': peer_ip = optarg; break;
            case 'p': port = atoi(optarg); break;
            case 'h': print_usage(argv[0]); exit(EXIT_SUCCESS);
            default: print_usage(argv[0]); exit(EXIT_FAILURE);
        }
    }

    if (!mode) {
        printf("[HOST_ERROR] Missing required argument: --mode\n");
        print_usage(argv[0]);
        exit(EXIT_FAILURE);
    }

    printf("[HOST] Starting Confidential P2P Node...\n");

    // Boot up the TEE (Trusted Execution Environment)
    if (init_enclave() < 0) {
        exit(EXIT_FAILURE);
    }

    // =========================================================================
    // LISTEN MODE (Server / Receiver Architecture)
    // =========================================================================
    if (strcmp(mode, "listen") == 0) {
        printf("[HOST] Node running in LISTEN mode on port %d\n", port);
        
        if ((server_fd = socket(AF_INET, SOCK_STREAM, 0)) < 0) {
            perror("[HOST_ERROR] Socket creation failed");
            exit(EXIT_FAILURE);
        }

        if (setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR, &opt_sock, sizeof(opt_sock))) {
            perror("[HOST_ERROR] setsockopt failed");
            exit(EXIT_FAILURE);
        }
        
        address.sin_family = AF_INET;
        address.sin_addr.s_addr = INADDR_ANY;
        address.sin_port = htons(port);

        if (bind(server_fd, (struct sockaddr*)&address, sizeof(address)) < 0) {
            perror("[HOST_ERROR] Bind failed");
            exit(EXIT_FAILURE);
        }
        
        if (listen(server_fd, 3) < 0) {
            perror("[HOST_ERROR] Listen failed");
            exit(EXIT_FAILURE);
        }

        printf("[HOST] Waiting for incoming encrypted untrusted packets...\n");
        
        // Blocking call: halts execution until a remote client connects
        if ((new_socket = accept(server_fd, (struct sockaddr*)&address, (socklen_t*)&addrlen)) < 0) {
            perror("[HOST_ERROR] Accept failed");
            exit(EXIT_FAILURE);
        }

        printf("[HOST] Peer connected! Reading raw payload from network stream...\n");
        ssize_t valread = read(new_socket, buffer, 1024);
        
        printf("[HOST] Received %ld bytes from network layer.\n", valread);
        printf("[HOST] Offloading encrypted payload to SGX Enclave via ECALL...\n");
        
        // ---------------------------------------------------------------------
        // PLACEHOLDER FOR ECALL DECRYPTION
        // Integrate your fork's specific decryption ECALL here.
        // Example: ecall_decrypt_packet(global_eid, buffer, valread);
        // ---------------------------------------------------------------------

        close(new_socket);
        close(server_fd);

    // =========================================================================
    // CONNECT MODE (Client / Transmitter Architecture)
    // =========================================================================
    } else if (strcmp(mode, "connect") == 0) {
        if (!peer_ip) {
            printf("[HOST_ERROR] Connect mode requires a target peer IP address (--ip)\n");
            exit(EXIT_FAILURE);
        }
        printf("[HOST] Node running in CONNECT mode. Target peer: %s:%d\n", peer_ip, port);

        if ((client_fd = socket(AF_INET, SOCK_STREAM, 0)) < 0) {
            printf("[HOST_ERROR] Socket creation error\n");
            exit(EXIT_FAILURE);
        }

        address.sin_family = AF_INET;
        address.sin_port = htons(port);

        if (inet_pton(AF_INET, peer_ip, &address.sin_addr) <= 0) {
            printf("[HOST_ERROR] Invalid address or address protocol not supported\n");
            exit(EXIT_FAILURE);
        }

        printf("[HOST] Connecting to remote peer...\n");
        if (connect(client_fd, (struct sockaddr*)&address, sizeof(address)) < 0) {
            printf("[HOST_ERROR] Connection Failed. Ensure the listener node is running.\n");
            exit(EXIT_FAILURE);
        }

        printf("[HOST] Connection established successfully.\n");
        printf("[HOST] Requesting sealed/encrypted secret from Enclave trust zone...\n");
        
        // ---------------------------------------------------------------------
        // PLACEHOLDER FOR ECALL ENCRYPTION
        // Generate secure encrypted payloads here inside the enclave before sending.
        // For testing, a dummy string is transmitted.
        // ---------------------------------------------------------------------
        char *dummy_encrypted_payload = "SGX_ENCRYPTED_DATA_STREAM_PLACEHOLDER";
        
        printf("[HOST] Transmitting payload over untrusted network socket...\n");
        send(client_fd, dummy_encrypted_payload, strlen(dummy_encrypted_payload), 0);
        printf("[HOST] Transmission complete. Closing socket connection.\n");

        close(client_fd);
        
    } else {
        printf("[HOST_ERROR] Invalid mode '%s'. Use 'listen' or 'connect'.\n", mode);
        exit(EXIT_FAILURE);
    }

    // Gracefully destroy the enclave session
    sgx_destroy_enclave(global_eid);
    printf("[HOST] Enclave destroyed. Node shutting down cleanly.\n");

    return 0;
}
